### ISSUE TITLE
Incorrect Keybindings Listed in Program

### ISSUE THREAD

**Issue by tmose1106** [richrd/suplemon#105]
I just tried out the suplemon.py to test out the editor a little, and the keybinding for Ctrl-W is incorrect. It say it is to duplicate lines, which is actually Ctrl-K. Not that big of an *issue*, but can't give a very good impression to first-time users. 

![1445782188](https://cloud.githubusercontent.com/assets/15310560/10716022/95f25060-7b00-11e5-8079-90b791277853.png)

**Comment by richrd** [comment]
Thanks for pointing this out! I forgot to update the legend when I changed the key binding.
Now the key legend is unfortunately still hard coded. I've been working on showing the legend based on real key bindings. That should hopefully be coming soon.

I manually corrected the key to `^K` in the dev branch for now.
