### ISSUE TITLE
Feature: Create missing directory when saving a file in a new location.

### ISSUE THREAD

**Issue by richrd** [richrd/suplemon#111]
Should probably ask whether the user wants the missing directories to be created.

**Comment by twolfson** [comment]
For reference, `pico` errors out saying "[ Error writing /home/todd/Desktop/hello/world.txt: No such file or directory ]"

When using the "Quick File Creator" plugin in Sublime Text 3, the plugin creates the directories without asking the user but doesn't save the scratch files.

When using "Side Bar Enhancements" plugin to move a file, the plugin creates all directories without asking the user.

**Comment by richrd** [comment]
For now I suplemon asks for wether the dir should be created.
