### ISSUE TITLE
Choose/disable flake8-quotes quote style from editor

### ISSUE THREAD

**Issue by equaeghe** [richrd/suplemon#113]
flake8-quotes by default uses '-quotes. Would it be possible to make it a configuration setting to choose the quote style (so also "-quotes) and moreover to disable flake8-quotes?

[BTW: I created a Gentoo ebuild; see https://bugs.gentoo.org/show_bug.cgi?id=573206 .]

**Comment by twolfson** [comment]
I don't quite follow the thread. `flake8-quotes` is a development dependency, not a runtime dependency. Is there any reason for it to be required in the package manager?

**Comment by equaeghe** [comment]
Well, flake8-quotes is active in suplemon when installed, so that was the reason for me asking. It seems I need to have a look at flake8 at and how it can be configured.

Is flake8-quotes used in tests?

**Comment by twolfson** [comment]
Ah, I see. `flake8` automatically picks up other installed extensions (e.g. `flake8-quotes`) but that isn't anything specific to the repo itself; that's specific to the OS.

http://flake8.readthedocs.org/en/latest/extensions.html

To prevent conflicting modules in a global environment, people typically use a `virtualenv`:

http://docs.python-guide.org/en/latest/dev/virtualenvs/

With respect to this repo, `flake8-quotes` is used during linting for consistent quotes:

https://github.com/richrd/suplemon/blob/v0.1.44/requirements-dev.txt

https://github.com/richrd/suplemon/blob/v0.1.44/test.sh#L5-L8

But to reiterate, `suplemon` has no runtime dependencies on `flake8` nor `flake8-quotes`.

https://github.com/richrd/suplemon/blob/v0.1.44/suplemon/modules/linter.py#L129-L131

https://github.com/richrd/suplemon/blob/v0.1.44/suplemon/modules/linter.py#L135

**Comment by richrd** [comment]
@twolfson Thanks for adressing this!

@equaeghe Your ebuild link doesn't seem to work for me. Could you check it? Also did you're issue get resolved?

**Comment by richrd** [comment]
Closing, reopen if you still have questions :+1:
