### ISSUE TITLE
Api editor

### ISSUE THREAD

**Issue by Alexey-T** [richrd/suplemon#115]
>    def run(self, app, editor, args):

U have here editior, ie ref to focused editor? CudaText has in API ref to focused editor AND to all other editors: maybe good to have here?

- object of curr editor 
- object of editor below current (split tab)
- func, which gets editors of all tabs in Cudatxt

**Comment by richrd** [comment]
Yes, `editor` is the current editor that is focused. The other open files can be accessed via `app.get_files()`. Currently split view isn't supported in Suplemon but probably will be later.
