### ISSUE TITLE
Make it clear how to disable INFO logs

### ISSUE THREAD

**Issue by Pajn** [richrd/suplemon#116]
There seems to be no documentation on how to change the default log level and I didn't find it by looking at the code either.

Should be pretty visible as other editors does not normally print to stdout.

**Comment by richrd** [comment]
Hi! Good point.

The documentation is still rather lacking, but I'll address this soon!

Thanks!

**Comment by richrd** [comment]
Hi again!

I've now released v0.1.45 with revamped logging and other improvements.
The logging level can be configured via the `debug_level` option in the configuration. 
To edit the config press <kbd>Ctrl</kbd>+<kbd>E</kbd> and run `config`. To view the default config run `config defaults`.

Hope this helps!

**Comment by Pajn** [comment]
Great, thanks!
