### ISSUE TITLE
Mac: Backspace key doesn't work

### ISSUE THREAD

**Issue by zenlc2000** [richrd/suplemon#13]
Great editor! One small issue - on my Mac the Backspace key produces ^?. Is there a config file where I can change that behavior?

Thanks
Mike

**Comment by richrd** [comment]
Thanks for the feedback!
Custom keyboard shortcuts aren't implemented yet, but they will be comming asap!
Meanwhile I'll try to add a keybinding that wil work on Mac too.

**Comment by richrd** [comment]
Could you try running the dev branch, and check if this fix works for you?

**Comment by zenlc2000** [comment]
Playing taxi for the family this morning. Will try it this afternoon when I
get back.

On Saturday, April 4, 2015, Richard Lewis <notifications@github.com> wrote:

> Could you try running the dev branch, and check if this fix works for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/richrd/suplemon/issues/13#issuecomment-89541274>.
>


-- 
"Human beings, who are almost unique in having the ability to learn from
the experience of others, are also remarkable for their apparent
disinclination to do so."
            - Douglas Adams

Excellent source of science-based strength and bodybuilding info:
http://www.clutchfitness.com/forums/?referrerid=2491

**Comment by marcelki** [comment]
Works now, i already tried it!

**Comment by richrd** [comment]
Thanks! :+1:

**Comment by richrd** [comment]
Apparently this is fixed now. I'll close the issue. If there's still problem just send a comment!
