### ISSUE TITLE
Feature proposal: Collaborative editing

### ISSUE THREAD

**Issue by richrd** [richrd/suplemon#132]
This is way out of the current project scope, but maybe, just maybe I'll do this one day.

It would be great if multiple people could edit the same file at once in real time.
The're are many things to consider. Here are some that come to mind:
- Should be implemented as a module. The core should be capable enough to support this.
- Should it work over the internet or only on localhost?
- How is a file opened or created in collaborative mode?
- Should collab mode be started automatically if someone opens a file that is already open in a suplemon process?
- Who is the master (and what does being master imply)? The person who opened the file first?
- It would be nice to see other peoples cursors (in different colors)
- How is the actual live syncing done?
  - One suplemon instance should act as the server
  - The other collaborators should be clients
  - If multiple files are edited in collab, should one or multiple sockets be used?
  - Changes should be represented as commands that can be serialized
  - Some locking will probably be needed so that each client gets its turn to send updates to the server
  - When a client doesn't have a lock, it can still edit the file, but the edits are stored in a command buffer until the client aquires the lock. Then it sends and empties the command buffer. 
  - When commands are received from clients the server should replay them in the editor. The master could receive commands from a client, run the commands and then relay the command to other clients.
- Lots and lots of other details...

**Comment by twolfson** [comment]
I believe the way Google Docs and Etherpad handle this is via diff-match-patch:

https://code.google.com/archive/p/google-diff-match-patch/

**Comment by richrd** [comment]
Cool, I'll look into that :+1:

**Comment by AllanLRH** [comment]
Another option could be Floobits – private worksplaces cost money, but it might be "easy" to implement, since they have an API with plenty of editors supported allready – and thus give collaborators a broad choice of editor :)
https://floobits.com/

**Comment by richrd** [comment]
Thanks for the idea!

I haven't heard of Floobits before. Floobits-support would definitely be nice even though it costs. I would probably want a Suplemon specific solution as well though.. Why not both :)

I wish could start implementing this one way or another, but at the moment I only have time to work on the core features. I'll get to this eventually though.

**Comment by juancarlospaco** [comment]
https://github.com/krishnasrinivas/nuttyapp#nutty-
With that you can do it, WebSockets or WebTRC.

**Comment by indolering** [comment]
Oh, there is totally a Python implementation of the Etherpad protocol!

**Comment by richrd** [comment]
I'll close this for now, since it's currently out of scope. Will revisit if I ever have time or if someone is willing to contribute towards an implementation.
