### ISSUE TITLE
Switch to asciimatics?

### ISSUE THREAD

**Issue by techtonik** [richrd/suplemon#137]
Looks like https://github.com/peterbrittain/asciimatics should work on Windows as well.

**Comment by twolfson** [comment]
`asciimatics` seems more targeted at animations than applications. I see some good code like 

https://github.com/peterbrittain/asciimatics/blob/8f0fb71c29ed72c03f80f2150258f54e8d8f91ea/asciimatics/screen.py

But there's also a lot of unnecessary code. What would be the benefits of using the library?

On a side note, if we are considering abstraction libraries, then maybe consider something like Blessed which is targeted at applications:

https://github.com/jquast/blessed

**Comment by richrd** [comment]
What I like about the current implementation is that it doesn't require any dependencies. However I don't like curses that much, so an abstraction library might be helpful. At the moment though I feel there are higher priority issues to take care of. 

If abstraction libs are used In the future it would be nice to be able to support multiple frontends in a modular way e.g. possibly even a GUI one day.

Time for sleep now, will think about this more tomorrow.

**Comment by richrd** [comment]
Closing for now, but I'll keep this in mind.
