### ISSUE TITLE
No response on Ubuntu

### ISSUE THREAD

**Issue by ChannelOne** [richrd/suplemon#14]
I cloned the project and typed `python3.4 main.py` in Terminal. The ui has loaded, but it had no response when I typed anything. The cursor could not blink and move.

When I typed `Ctrl + C` to kill it. It printed:

````````````````python
Traceback (most recent call last):
  File "/home/devis/suplemon/main.py", line 443, in <module>
    ui.wrapper(main)
  File "/home/devis/suplemon/ui.py", line 22, in wrapper
    curses.wrapper(func)
  File "/usr/local/lib/python3.4/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/devis/suplemon/main.py", line 436, in main
    app.run()
  File "/home/devis/suplemon/main.py", line 70, in run
    self.main_loop()
  File "/home/devis/suplemon/main.py", line 78, in main_loop
    self.ui.update()
  File "/home/devis/suplemon/ui.py", line 164, in update
    self.check_resize()
KeyboardInterrupt
````````````````

but sometimes it printed:

`````````````````python
Traceback (most recent call last):
  File "/home/devis/suplemon/main.py", line 443, in <module>
    ui.wrapper(main)
  File "/home/devis/suplemon/ui.py", line 22, in wrapper
    curses.wrapper(func)
  File "/usr/local/lib/python3.4/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/devis/suplemon/main.py", line 436, in main
    app.run()
  File "/home/devis/suplemon/main.py", line 70, in run
    self.main_loop()
  File "/home/devis/suplemon/main.py", line 80, in main_loop
    event = self.ui.get_input()
KeyboardInterrupt
`````````````````

It is so strange.

**Comment by richrd** [comment]
Thanks for the info! I'm on Kubuntu and I can't reproduce the problem with python3.4. I'll check again on a fresh Ubuntu install, and see what happens.

**Comment by ChannelOne** [comment]
Thanks！I use Ubuntu 12 LTS. I installed Python3.4 from PPA, but it has not
curses module so I compiled from source code and copied the _curses*.so
file to the installed Python. I don't know if the curses module caused the
problem. So I provide more information s to you.

Thanks for the info! I'm on Kubuntu and I can't reproduce the problem with
python3.4. I'll check again on a fresh Ubuntu install, and see what happens.

—
Reply to this email directly or view it on GitHub
<https://github.com/richrd/suplemon/issues/14#issuecomment-89594538>.

**Comment by richrd** [comment]
Good to know, I tried Ubuntu 14.04.2 LTS and Suplemon worked out of the box. I'll try 12 LTS when I get a chance. I'll let you know what results I get.

Python 3 is needed for the some curses features, that don't exist in Python 2. Especialy the `curses.get_wch` method. Could it be that the curses source wasn't the latest version for Python 3?

**Comment by ChannelOne** [comment]
I think I knew the problem. 
The code:
````````````````python
    def get_input(self):
        """Get an input event from keyboard or mouse. Returns False or an InputEvent instance."""
        char = False
        event = InputEvent()
        try:
            char = self.screen.get_wch()
        except KeyboardInterrupt:
            event.set_key_name("^C")
            return event
        except:
            return False
````````````````

when I removed try/catch, I found that:
```````````````````python
  File "/home/devis/suplemon/ui.py", line 351, in get_input
    char = self.screen.get_wch()
AttributeError: '_curses.curses window' object has no attribute 'get_wch'
```````````````````

In my python, `windows` object has no `get_wch` method? I downloaded the source(3.4.3) and compiled again. But the problem didn't solve, how to solve it?

**Comment by richrd** [comment]
Thanks for finding the reason!

It's weird because get_wch was added in Python 3.3. I also had some curses problems when I tried to compile Python myself. I'll try to find out how to get the new curses module working on Ubuntu 12 today.
I'll let you know what I find.

**Comment by richrd** [comment]
Update: I added experimental Python 2 support in the dev branch (only ASCII characters work). You could try that meanwhile I try to solve the real curses problem.

**Comment by ChannelOne** [comment]
Alright! Thank you very much.
2015年4月6日 上午12:43于 "Richard Lewis" <notifications@github.com>写道：

**Comment by richrd** [comment]
Hi! You could try this to install Python 3.4 from this repository. It worked for me on a fresh Ubuntu 12 Virtual Machine.
```
sudo add-apt-repository ppa:fkrull/deadsnakes
sudo apt-get update
sudo apt-get install python3.4
```
Let me know if it helps.
For me that fixed the get_wch problem, but there are still some problems with some keys. On Ubuntu 14 everything works fine.

**Comment by ChannelOne** [comment]
Thanks! I am busy and I have to try it at this weekend. I will tell you
after trying. Although I am considering to upgrade to Ubuntu 14 , I think
it's necessary to support old version because many servers still use it.
You did a good job.
2015年4月6日 下午10:45于 "Richard Lewis" <notifications@github.com>写道：

**Comment by richrd** [comment]
Thanks for your response! It's good that you're going to upgrade to 14. That should solve all the problems you are having.
However I mostly agree with supporting old versions too. Unfortunately the old curses makes it impossible to support special characters and some special keys properly. Only ASCII characters are officaly supported in Python < 3.3 and some keyboard shortcuts won't work. 

I did some testing, and it seems that **fully** supporting the old Python would bee a lot work, if not impossible. For now I'm mainly focusing on Python 3.3 or higher. I'm sorry about that.

**Comment by richrd** [comment]
Hi, I've added some support for Python < 3.3 into the master branch. Hope you're able to get started with the editor now.

**Comment by ChannelOne** [comment]
Thank you. I have tried it and it's solved.
