### ISSUE TITLE
[Rewrite] commands should be compatible with sublime text

### ISSUE THREAD

**Issue by richrd** [richrd/suplemon#145]
Currently suplemon has lots of command similar to sublime, except that the naming is different.
For example we have 'close_file' and sublime has 'close'.

**Comment by richrd** [comment]
This will probably be part of the #161 overhaul.

**Comment by FranzSkuffka** [comment]
external consistency is a great argument from a UX perspective for this design choice.

**Comment by richrd** [comment]
Closing for cleanup, will be looked at during the rewrite.
