### ISSUE TITLE
Feature proposal: Wrap text

### ISSUE THREAD

**Issue by alexmigf** [richrd/suplemon#148]
Wrap text that goes above the window width.

**Comment by richrd** [comment]
Thanks for the suggestion!

I've thought about doing it, but haven't needed it enough to actually do it yet.

This again is something that unfortunately needs some refactoring before it can be done :/. The rendering part isn't very hard, but it should also change the behaviour of some commands. If I only changed the rendering, then when pressing down on the first row of a wrapped line, the cursor would jump to the next "real" line and not the next row of the wrapped line.

Like this (The `|` symbol is the cursor)
```
01 print("Very| long text here. Very long text here. Very long text here. Very long
     text here. Very long text here. Very long text here. Very long text here.")
02 # A comment line here ...
``` 
Pressing the down arrow would show:
```
01 print("Very long text here. Very long text here. Very long text here. Very long
     text here. Very long text here. Very long text here. Very long text here.")
02 # A comment| line here ...
```
The desired result would really be this:
```
01 print("Very long text here. Very long text here. Very long text here. Very long
     text here.| Very long text here. Very long text here. Very long text here.")
02 # A comment line here ...
```
Anyway this is an important feature so I'll keep this open and try to get it done when I have time :)

**Comment by alexmigf** [comment]
Sure, just an idea :)

**Comment by richrd** [comment]
Closing for now, will revisit during the rewrite.
