### ISSUE TITLE
Feature proposal: Terminal

### ISSUE THREAD

**Issue by alexmigf** [richrd/suplemon#149]
Possibility to open a split terminal window (on bottom for example) to be able to run something at the same time in a faster way and without leave the current window.

**Comment by twolfson** [comment]
By terminal, do you mean something as in the existing terminal session (e.g. `bash`, `zsh`) or Python (e.g. Sublime Text)?

**Comment by alexmigf** [comment]
Bash or zsh.

**Comment by twolfson** [comment]
Heh, yep. I was going to say it's YAGNI/breaks the Unix Philosophy as `tmux` can handle that and much more =P

**Comment by alexmigf** [comment]
I know some editor that does that, don't remember now if it's jed or other.

**Comment by richrd** [comment]
I agree that this could be nice to have, but also think that tmux would probably do the job better.
If I'm on a server without tmux I usually just SSH into it with two different terminals.

I wouldn't object if someone wants to implement this as a module when the API supprts it, but unfortunately I won't have time to do it, so I'll close this for now.
