### ISSUE TITLE
Suggestion for refactoring

### ISSUE THREAD

**Issue by eugene-eeo** [richrd/suplemon#15]
Hi, nice work on the editor! You should consider this when refactoring the code- currently in line 606, file ``editor.py`` there is a huge conditional with lots of branches for comparing the keys. What I suggest is that you instead use a dictionary to hold all the callbacks, i.e.

```python
class Editor(Viewer):
    key_mappings = {}
    #...

Editor.key_mappings.update({
    curses.KEY_RIGHT: dispatch('arrow_right')
})
```

Where ``dispatch`` is a function that returns a closure that when called with an instance, it dispatches to the enclosed attribute. Then the code in ``handle_input`` would be easier to implement as well:

```python
def handle_input(self, event):
    if event.type == "mouse":
        return False
    key = event.key_code
    if key in self.key_mappings:
        self.key_mappings[key]()
        return
    try:
        self.type(key)
    except:
        pass
```

Pragmatic considerations aside, this also trades space for time, as the conditional runs in **O(n)**, where **n** is relative to the key. This implementation runs in **O(1)**, and also allows plugins to map keys to their own callbacks, a la Vim. Also it reflects the mental model of the editor being a program that just responds to events and acts on the text. You can also use a list to store the callbacks to be invoked when keys are pressed, but that's another story.

**Comment by richrd** [comment]
Wow, thanks very much for your suggestion! I really appreciate your effort :+1: I agree that the `handle_input` method needs improvement. I'm going to support custom key bindings so refactoring is important. Also good point about allowing the plugins to register their keybindings.
This is high on my priority list so I'll start working on it soon.

Thanks!

**Comment by richrd** [comment]
Custom key bindings are now implemented.
