### ISSUE TITLE
Feature proposal: Autocomplete with Open File

### ISSUE THREAD

**Issue by alexmigf** [richrd/suplemon#151]
Will be good to have autocomplete when opening files inside the editor.

**Comment by richrd** [comment]
Good idea! Would be nice to have until I get the proper file explorer implemented.

**Comment by defnull** [comment]
Yes please. That was the first thing I noticed missing.

**Comment by richrd** [comment]
I've taken this on. My initial progress is in the https://github.com/richrd/suplemon/tree/file-autocomplete branch. Maybe you guys could test? I'll be testing it with my setups too.

**Comment by alexmigf** [comment]
Doesn't seem to work for directories, only files.
