### ISSUE TITLE
comparison to kakoune

### ISSUE THREAD

**Issue by FranzSkuffka** [richrd/suplemon#153]

**Comment by richrd** [comment]
Could you elaborate? Suplemon could be compared to any editor out there, but I don't think this is the right place for publishing comparisons.

**Comment by richrd** [comment]
Closing until further info is provided.

**Comment by FranzSkuffka** [comment]
kakoune is an editor that also leverages the power of multiple cursor but is merely a successor of vim rather than sublime text. These two editors struck me as competitors. Kakoune is designed orthogonally and possibly embeddable with the concept of suplemon.

**Comment by richrd** [comment]
Fair point. Maybe I'll find some cool stuff in kakoune to implement in Suplemon. However I haven't compared it to much since I initially created the editor for myself. Since Suplemon has become a lot more serious over time I should probably look into other editors more to maybe leech some features ;)

**Comment by FranzSkuffka** [comment]
I think it's going to be hard closing the gap with 8x more commits on kakoune. They have a pretty performant implementation of multiple cursors including selections already. I will track suplemon from now on.

**Comment by richrd** [comment]
You're right, and I don't expect Suplemon to ever "beat" vim, emacs or kakoune etc. It's a different concept that I'm working on (primarily for myself for fun, even though it's more serious now). I call it "nano on steroids with sublime text flavour" and someone on twitter called it "the bastard child of Sublime text and Nano" which I find quite funny (and true). There's still lots of core things to work on like the event and plugin architecture as well as wrapping lines etc etc.

That said I still hope that Suplemon has its own niche. It's mainly for people that want a "powerfull" editor that they can "just use" but without all the learning curve. Stuff like modes/macros/chords/whatever isn't (currently) supported at all. For users of vim, emacs, kakoune etc: this probably won't be for you (at least for a while).

**Comment by FranzSkuffka** [comment]
Well I haven't really tried suplemon yet but I feel that I had a valuable contribution here. Possibly suplemon might be the right software for fellow developers that want to dig into the possibilities of the CL without all the steep learning curve, as you said.

After all, I want to thank you for sharing your work, like any OSS contributor :)

**Comment by richrd** [comment]
I do think your views are valuable, and I'll take them into account while developing. I do think there's lots to be done and lots of it overlaps with kakoune and other editors. Sorry for closing this fast, I didn't really get what you wanted to say at first. Thanks for sharing your toughts :+1:

And thanks for the thanks! :) It's been loads of fun to share the project and get reactions from the community for something I created.
