### ISSUE TITLE
Package Installers

### ISSUE THREAD

**Issue by indolering** [richrd/suplemon#165]
It would be really nice if I could just type `sudo apt install suplemon` into my terminal : )

**Comment by richrd** [comment]
I fully agree, it would be nice to get suplemon into the official repositories of debian and other distributions too. That might take some time though, because I'd need to create the package and get it approved. Let me know if you have any tips on the process.

Meanwhile you can use `sudo pip3 install suplemon` as long as you have `pip3` installed first. Hopefully that's good enough for now.

**Comment by indolering** [comment]
Start out with the [OpenSuse Build Service](https://build.opensuse.org/) to get started.  Then, after you've gotten some traction within distro X, a fan can step in and work on getting it upstreamed to the official repos.

**Comment by richrd** [comment]
Looks good! I'll try that route.

**Comment by juancarlospaco** [comment]
```
# To generate DEB package from Python Package:
sudo pip3 install stdeb
python3 setup.py --verbose --command-packages=stdeb.command bdist_deb

# To generate RPM package from Python Package:
sudo apt-get install rpm
python3 setup.py bdist_rpm --verbose --fix-python --binary-only
```

**Comment by richrd** [comment]
@juancarlospaco Wow, thanks! That looks really handy. Tried both commands and they worked perfect.

**Comment by juancarlospaco** [comment]
```
# To generate EXE MS Windows from Python Package (from MS Windows only, with all Dev Libs installed):
python3 setup.py bdist_wininst --verbose
```
Not tested myself, since I dont use Windows, but that should do according to docs.

**Comment by indolering** [comment]
Argh, once I sit down and wrangle my own CI workflow I will try to put together something for Suplemon.  I would like to see all of the major platform supported.

**Comment by richrd** [comment]
Closing this as I don't have time to build and maintain packages for different distros. I'll revisit this when I do, but in the mean time it seems like people have already created some packages:
- https://aur.archlinux.org/packages/suplemon/
- https://fedora.pkgs.org/26/rpm-sphere/suplemon-0.1.64-4.1.noarch.rpm.html
