### ISSUE TITLE
Cursor Support

### ISSUE THREAD

**Issue by indolering** [richrd/suplemon#167]
Can I not use the mouse to alter the location of the cursor?

**Comment by richrd** [comment]
You can :) It's available by enabling mouse mode with <kbd>F8</kbd>. A left click will move the cursor, and a right click will add a new cursor at the click position.

Now that I think of this, there should be a setting for permanently enabling mouse mode...

**Comment by indolering** [comment]
Why wouldn't this be turned on by default?

**Comment by richrd** [comment]
Because that disables selecting text with the mouse for copying and pasting. It also disables the right click context menu in terminals. Also partly because I think the text selecting ability is more used than moving the cursor with the mouse. Either way, it needs to remain toggleable. Not quite sure whether it would be best to have it on or off by default.

Text selection with the mouse could be implemented within Suplemon, but that requires refactoring the core to allow for internally selecting text in the first place. It's on my to-do list but it'll take some time.

**Comment by indolering** [comment]
Is there no way to have a traditional text based input experience in the console?

**Comment by MrDowntempo** [comment]
Yeah? Something like having a click always move the cursor, but if it's a 
click and hold, start the selection and let the mouse drag to the end of 
the selection?

**Comment by richrd** [comment]
There probably is a way, though I'm not sure if it would be very reliable. The curses terminal library doesn't seem to handle the mouse very consistently. 

I guess you're looking for something like this ![Mouse Selection](https://media.giphy.com/media/3o85xBUSxteQlG5R1m/giphy.gif)

Anyway I'll need to implement selection support within Suplemon first, which isn't a simple task. After that's done the mouse support can be added. Then we could probably ditch "mouse mode" and just have it always on.

**Comment by twolfson** [comment]
I concur that mouse selection is likely very difficult to implement. `nano` only implements jumping on click (but then again, it doesn't have selection either).

I think this issue has gotten off-topic, we should prob break out "Selection support via mouse" into its own separate issue and leave this as an issue about setting a permanent flag for cursor jumping via mouse.

**Comment by twolfson** [comment]
As a devil's advocate, I don't think mouse mode should always be enabled. In my experience with `nano`, I will sometimes use the mouse to switch window focus but `nano` can't distinguish the intention of my click (i.e. it doesn't know the window was out of focus) so it will jump and I lose my location =/

**Comment by indolering** [comment]
Would it be easier if the terminal/window manger helped out?  We are all using virtual terminals now, it's about-damn-time that we gained the ability to edit content with the cursor.

**Comment by richrd** [comment]
The focus issue might be something that the Gnome Terminal and iTerm teams might be able to fix, but other than that, there's not much that they can do. I've done some experimenting with the mouse support recently and it looks like it will be possible to implement *better* mouse support (maybe with selections too). If and when I get selections implemented in Suplemon I'll get back to this.

However the original issue is already implemented, so I'll close this for now.

**Comment by richrd** [comment]
Also for the record I realized that also the config option for the mouse mode is implemented. It's `use_mouse` in the `editor` section in the config file. Can't believe I'd forgotten I implemented that.
