### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by indolering** [richrd/suplemon#177]
I know this will be controversial, but Suplemon is just too hard to remember and takes too long to type!  How are we supposed to compete with much hipper names like LimeText and Slap :wave: and Micro?  

What about Supl?

**Comment by richrd** [comment]
It sure is a weird name. Personally I don't think it's that hard to remember (big surprise), think of it as Super Lemon. For typing I recommend just aliasing it. I use `alias sl="suplemon"`. I'm not 100% against renaming but I don't feel it's justified in terms of return of investment.

**Comment by richrd** [comment]
Closing this as I don't think it's worth it. I also don't want to rename the repository since the it already has some link weight.

**Comment by indolering** [comment]
;)
