### ISSUE TITLE
Add #console etc. keywords to repo

### ISSUE THREAD

**Issue by ozra** [richrd/suplemon#180]
I was busy, now that I have a break I wanted to get back to this and try the editor, but couldn't find it via google until I had searched like five times with different phrases.

First I searched was "sublime like open source console editor"

There's probably more people looking for something like this - so it's good if it's found when searching on relevant terms, just my 2 satoshi.

You can close this when you've seen it. Cheers, now I'm gonna try it :-)

**Comment by richrd** [comment]
Great that you found it! I've tried to get some better google rank, but it's not easy. I added the console keyword just now :+1: I should probably setup a website for it or something. Currently suplemon doesn't yet have all the features I want so I'll work on them first though.
