### ISSUE TITLE
Shift+← to select things

### ISSUE THREAD

**Issue by nargyriou** [richrd/suplemon#185]
Hi, I just discovered the project. A very common thing that I do in sublime text is use the shift key to make selections, from where the cursor now is to where the cursor was when I started pressing shift.

* <kbd>Shift</kbd>+<kbd>←</kbd> Select the character before the cursor
* <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>←</kbd> Select the last word
* <kbd>Shift</kbd>+<kbd>→</kbd> The next character
* <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>→</kbd> The next word
* etc...

I wonder if it'd be possible to add that feature in Suplemon ?

**Comment by richrd** [comment]
Selections aren't yet supported, but it seems to be the most wanted feature. The selection keys you mentioned will be implemented in the rewrite that I'm working on. I haven't had much time to work on it lately and it will take some time before the rewrite is in a usable state. I'll let you know when it can be tested.

**Comment by Consolatis** [comment]
I was thinking a bit about what is required to implement selections:
{shift,shift+ctrl}+{left,right,up,down,home,end,pageup,pagedown,mouseleft} checks if self._selection_start is None:
- if yes: sets self._mark_start to current cursor position (y, x) (before processing the given action)
- if no: current cursor position acts as implicit self._selection_end (after processing the given action)
- If some other key is pressed self._selection_start is reset to None.

To visualize the selection, while rendering lines something like this is added:
```python
if self._selection_start is not None and self._selection_start[1] == y:
    # Some magic to keep track of written characters for tokens of this line and at the
    # right position change the background attributes set to A_REVERSE or A_STANDOUT.
if self._selection_start is not None and self.get_cursor()[1] == y:
    # Same magic to keep track of written characters for tokens of this line
    # and at the right position reset background attributes to their previous state.
```
This would allow all the syntax highlighting to keep working. And by having self._selection_start and self.get_cursor(), commands like c-x or c-c have access to positions inside self.lines() and can use them to e.g. cut the whole selection.

**Comment by richrd** [comment]
I won't be able to get this into the current codebase selections (regions) will eventually be part of the core rewrite. Unfortunately there's no timeframe for that at the moment. I will revisit this during the refactor developement. Closing for now.
