### ISSUE TITLE
Ctrl+Backspace to delete a whole word ?

### ISSUE THREAD

**Issue by nargyriou** [richrd/suplemon#186]
This is something that I do all the time, even as I'm writing this; keeping the <kbd>Ctrl</kbd> down broadens the range of whatever action you were doing

* <kbd>Ctrl</kbd> + <kbd>←</kbd> to move back one word, 
* <kbd>Ctrl</kbd> + <kbd>Backspace</kbd> to delete one word,
* <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>←</kbd> to select the last word,
* etc...

Considering the limitations of the terminal, I don't know if that'd be possible. But I'd sure like it if it was added :)

**Comment by richrd** [comment]
The general idea will be implemented (in the rewrite), but unfortunately there doesn't seem to be any way to detect <kbd>Ctrl</kbd> + <kbd>Backspace</kbd> or <kbd>Shift</kbd> + <kbd>Backspace</kbd>.

I can only detect <kbd>Alt</kbd> + <kbd>Backspace</kbd> so that will surely be used for something.

**Comment by richrd** [comment]
Closing this as <kbd>ctrl</kbd> + <kbd>backspace</kbd> will probaby never be implemented. This is due to terminal limitations. The same functionality will be implemented via <kbd>alt</kbd> + <kbd>backspace</kbd> in the rewrite.

**Comment by Consolatis** [comment]
At least in tmux and mate-terminal I get keycode 8 for ctrl+backspace and keycode 263 for backspace.
I do not get anything different for shift+backspace though:
```python
#!/usr/bin/env python3

import curses

def main(stdscr):
    stdscr.idlok(1)
    stdscr.scrollok(1)
    keys = dict((getattr(curses, key), key) for key in dir(curses) if key.startswith('KEY_'))
    while True:
        key = stdscr.getch()
        stdscr.addstr("Got key: %3s %s\n" % (key, keys.get(key, '.')))
        stdscr.refresh()
        if key == ord("q"):
            break

curses.wrapper(main)
```

Btw how do you create those keyboard signs in markdown?

**Comment by richrd** [comment]
Oh cool! I didn't know that <kbd>ctrl</kbd>+<kbd>backspace</kbd> actually does work in some terminals. It just didn't work in the ones I use. I guess keycode 8 should be added to the key mappings.

The keyboard signs can be created with < kbd >key</ kbd >

**Comment by richrd** [comment]
I just realized that the example uses `getch` instead of `get_wch`. Suplemon uses `get_wch` to allow getting unicode characters (e.g. 'ä'). I tested this with `get_wch` and <kbd>ctrl</kbd>+<kbd>backspace</kbd> gives '\x08' which should work fine.

**Comment by richrd** [comment]
Eh, I just realized something else which I've discovered earlier: <kbd>ctrl</kbd>+<kbd>backspace</kbd> and <kbd>ctrl</kbd>+<kbd>h</kbd> both return '\x08' so we have no idea which of them was actually pressed... meh. :confused:

**Comment by richrd** [comment]
Closing due to the above.
