### ISSUE TITLE
I keep getting the help screen.

### ISSUE THREAD

**Issue by Wyvern67** [richrd/suplemon#190]
I like having a help screen, but I'm starting to hate this one.
There's a shortcut that displays it - I don't know it, but it's there. The help screen keeps popping up
At first I didn't know what it was or why it was here (frustrating), and it took me a while to understand how to exit it.

I think it would be good design to remove that shortcut

**Comment by richrd** [comment]
Hi and sorry that I forgot about this.

How do you feel about this issue at the moment? Did you find that the shortcut is <kbd>ctrl</kbd> + <kbd>H</kbd>? Do you think it could be clarified better? It might be nice to remove it altogether and use it for something better. However I'd like to keep it easy to find and open the help screen. Would you have some suggestions?
