### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by Gnewbee** [richrd/suplemon#194]
The project may benefit from having sub packages for grouped functionnality

**Comment by richrd** [comment]
That's true! I'm working on a more modular and maintainable codebase where I try to address all the issues in the current version. Right now it's not usable at all as I'm currently just developing a curses abstraction. If you want to check that out it's here: https://github.com/richrd/suplemon/tree/rewrite-dev

**Comment by richrd** [comment]
Would you have examples of functionality that should be grouped? I'd like to hear so I can design and implement the rewrite better.

**Comment by richrd** [comment]
Closing this as it'll be adressed in the rewrite.
