### ISSUE TITLE
"suplemon.config - INFO - Failed to load config file" log on close

### ISSUE THREAD

**Issue by bagage** [richrd/suplemon#196]
Anytime I edit some file with suplemon (best CLI text editor!), this message appears in logs:

> 2017-09-20 14:49:56,142 - suplemon.config - INFO - Failed to load config file '/Users/user/.config/suplemon/suplemon-config.json'.

It happens both on MacOSX and Debian - I tried to create an empty file and also put an empty JSON in it `{}` but the message is still here:

```
$ cat $HOME/.config/suplemon/suplemon-config.json
{}%
$ suplemon $HOME/.config/suplemon/suplemon-config.json
2017-09-20 14:49:56,142 - suplemon.config - INFO - Failed to load config file '/Users/user/.config/suplemon/suplemon-config.json'.
```

On MacOSX I'm running suplemon 0.1.61 installed via pip3.

**Comment by richrd** [comment]
Thanks for reporting. Your config seems to be correct. I'll look into this hopefully today.

**Comment by richrd** [comment]
I'd overlooked that an empty dict is Falsy in Python. It's now fixed in the dev branch and I'll release a new version in the near future.
