### ISSUE TITLE
Invalid cursor position saved

### ISSUE THREAD

**Issue by bagage** [richrd/suplemon#198]
I don't know if there are any alternative to the current behavior, but the "save cursor position" feature is strange when you use suplemon as your git editor for instance:

Everytime you type `git commit -a`, suplemon is invoked so that you can type your comment. But `git` actually opens a file `COMMIT_EDITMSG`. If you type, say, a 4 lines commit, then on your next commit the cursor will be down to be 4th line because this is still the "same" file `COMMIT_EDITMSG`. The same strange behavior happens for `git rebase` and such obviously.

One possible behavior could be to restore cursor position only when the file content is the same as previously (checksum or equivalent)? I'm not sure it make senses to restore cursor position when file has been modified by any other software - what do you think?

**Comment by richrd** [comment]
Good point! I've noticed this a few times but haven't been too bothered with it. However your use case is such that this feature might be rather annoying. I think the best approach is to save a hash/checksum of the file too, and only restore the cursors if the hash is the same as before. I'll fix this for the next release.

**Comment by richrd** [comment]
This is now fixed in the dev branch. Please test it if you have time.

**Comment by bagage** [comment]
Cool, thanks, I'll give it a try today.

**Comment by bagage** [comment]
So far so good. Did not see any issue yet.

**Comment by bagage** [comment]
As of today, I only saw one strange behavior once but not sure it was related to this bug. Apart of that it works great :).
