### ISSUE TITLE
Use of native methods/functions

### ISSUE THREAD

**Issue by Gnewbee** [richrd/suplemon#202]
Some functions seem to reimplement functionality that is present in the standard library, e.g. helpers.starts and helpers.ends reimplement s.startswith(pattern) and s.endswith(pattern) but are less efficient. This should be replaced. Also, Viewer.pad_lnum is essentially s.zfill(n).

**Comment by richrd** [comment]
Thanks for finding these! I should have realized that python must have those built in.

**Comment by richrd** [comment]
This is now released! :+1:
