### ISSUE TITLE
Refactor Cursor class

### ISSUE THREAD

**Issue by Gnewbee** [richrd/suplemon#203]
I want to refactor the cursor class to:

1.     Use properties instead of simple accessors
2.     add `__gt__` so that cursors become sortable (used extensively e.g. in editor.py and viewer.py)
3.     Remove `__getitem__` (not necessary with simple properties us c.x and c.y)

**Comment by richrd** [comment]
Sounds good! The sorting is a really nice idea.
If I remember correctly the x and y are sometimes accessed via [0] and [1]. That should be checked to make sure nothing breaks.

**Comment by richrd** [comment]
Are you still interested in doing this? if you are feel free to drop a PR! I'll close this issue for now.
