### ISSUE TITLE
Diff/merge features

### ISSUE THREAD

**Issue by MrDowntempo** [richrd/suplemon#205]
Libdiff is a good diff library written in Python. This could be great for using suplemon to manage diff comparisons. It night be better as a plug-in when that API is done?

**Comment by richrd** [comment]
Not 100% sure what your use case is, but suplemon currently has a diff command (plugin) for viewing a diff of the current file in the editor vs the same file on disk. You can run it by hitting <kbd>ctrl</kbd>+<kbd>e</kbd> typing `diff` and pressing enter. It uses pythons built in `difflib`.

**Comment by richrd** [comment]
Closing this since a diff command is already available. Feel free to reopen if this is still an issue.
