### ISSUE TITLE
Powerline integration

### ISSUE THREAD

**Issue by MrDowntempo** [richrd/suplemon#206]
Powerline is a plug-in for Vim written in Python that puts a lot of handy UI on one line at the bottom of the editor. It might be possible to fork/merge it into suplemon?

**Comment by richrd** [comment]
Thanks for the suggestion! It would likely be useful but it'd be a lot of work to add and I'd rather be in favor of plugins for suplemon. They can already add info to the top and bottom status bars so it's trivial to write plugins for displaying extra stuff there.
