### ISSUE TITLE
Documentation for commands.

### ISSUE THREAD

**Issue by richrd** [richrd/suplemon#207]
Document all the commands available in suplemon. The documentation should be included in the readme and in the built in help feature.
A nice way to do that might be adding docstrings to all the modules in suplemon and then autogenerate the docs from them. Simple description, purpouse and usage should be enough.

**Comment by MrDowntempo** [comment]
I thought I might try to tackle this a little since it seems relatively easy for a newbie programmer like myself. Just to understand better, you're hoping info like CTRL-S to Save would be included in the docstring of the relative function? Like  ```
def save_file_as(self, file=False):
"""Save current file."""
```

**Comment by richrd** [comment]
Thanks for the comment! Yeah, generally all user interactions should have docs but I was mainly thinking about the add-on modules that are available, like `reverse`, `upper` and `comment`. Many of these are really simple and as such don't really require much documentation. However it would be good to have docstrings for all functions, especially ones that are related to user interaction.

The goal for this issue is to write sufficient docs for the add-on modules and then have some script extract the docs and place them in the readme and the help file. I've more or less finished the module docs in this branch: https://github.com/richrd/suplemon/tree/module-docs I haven't worked on the doc generator yet though.

**Comment by richrd** [comment]
Documentation has
