### ISSUE TITLE
[Rewrite] Context sensitive legend and below or above bottom status line

### ISSUE THREAD

**Issue by Consolatis** [richrd/suplemon#223]
I just recognized nano positions the bottom status line above its legend.
The nano legend is also context sensitive, e.g. it shows key bindings for the current prompt or generic key bindings if no prompt is active:
Search (c-w) differs from Write Out (c-o) which differs from no prompt active.

I have no strong opinion about any of these as I usually disable the legend anyway.

**Comment by richrd** [comment]
Good observations, you're on a roll! It's nice to see so much enthusiasm :)
The context sensitive legend would be good to have. For example the prompt in the bulk_delete command binds the arrow keys to delete directions which isn't clear to the user.

I'll try and find time to go throgh all your contributions this week. Probably during the weekend at the latest. And thanks, I really appreciate your effort! :+1:

**Comment by Consolatis** [comment]
No worries, take your time.
Status components will take a bit before being in a state I'd call RFC worthy anyway and I can rebase the status component branch regularly on feature/colorpairs so I am not blocked to work on either of them.

**Comment by richrd** [comment]
I decided that this would be best implemented in the rewrite. It's a lot of work and needs a solid spec and implementation plan to make it happen.
