### ISSUE TITLE
multiple files like nano?

### ISSUE THREAD

**Issue by meoso** [richrd/suplemon#226]
Can suplmon take multiple filesnames as parameters like nano?  
I tried, but only one file is loaded or am i doing it wrong?  in Nano, as i exit the first file, the next file will focus.

**Comment by richrd** [comment]
Yeah, you can open as many files as you want. You can switch between them with <kbd>ctrl</kbd>+<kbd>page up</kbd> and <kbd>ctrl</kbd>+<kbd>page down</kbd>. The different files whould be visible as "tabs" at the top of the screen.

**Comment by meoso** [comment]
i can't seem to ctrl-pgup / ctrl-pgdn in my xfce4-terminal. i guess those keys are already bound.

**Comment by richrd** [comment]
Hmm, maybe you can change the bindings in your key config. <kbd>shift</kbd> + <kbd>left/right</kbd> seems to work.
You can add this to your keymap to change the keys. You can open the keymap by pressing <kbd>ctrl</kbd>+<kbd>e</kbd> and running the "keymap" command.
```
[
    {"keys": ["shift+left"],    "command": "prev_file"},
    {"keys": ["shift+right"],   "command": "next_file"}
]
```
