### ISSUE TITLE
[Wishlist] in multi cursor mode execute find for each cursor

### ISSUE THREAD

**Issue by Consolatis** [richrd/suplemon#227]
Or provide a second function like find which works for multi cursor.
That would actually be more useful because then find can still be used to create multiple cursors.

e.g. if we have following code:
```
        # backspace is tricky:
        # ctrl+backspace returns keycode 8
        # backspace returns keycode 127/KEY_BACKSPACE
        _fmt("backspace"):                         127,
        _fmt("backspace"):                         "KEY_BACKSPACE",
        _fmt("backspace", "alt"):                  "m-KEY_BACKSPACE",
        _fmt("backspace", "alt"):                  "m-c127",
        _fmt("backspace", "alt", "ctrl"):          "m-c8",
        _fmt("backspace", "ctrl"):                 8,
        # additional modifyOtherKeys variants
        _fmt("backspace"):                         "c127",
        _fmt("backspace", "alt", "ctrl"):          "m-c-c8",
        _fmt("backspace", "alt", "ctrl", "shift"): "m-c-s-c8",
        _fmt("backspace", "alt", "shift"):         "m-s-c127",
        _fmt("backspace", "ctrl"):                 "c8",
        _fmt("backspace", "ctrl", "shift"):        "c-s-c8",
        _fmt("backspace", "shift"):                "s-c127",
```
Target: convert it into a format like (last line as example) `add("shift", "backspace", "s-c127")`
That is, move "backspace" to be the second last parameter and replace "_fmt" by "add" and "):" by "," and ",$" by ")".
- "multi-cursorize" all _fmt lines
- Home, remove "_fmt", write "add"
- position the cursors on the start of "backspace, " and delete
- this does not work:
  - c-f to search for ":"
  - delete "):", write ', "backspace",'
- End, remove ",", write ")"

Edit:
Just recognized I don't need to move the parameter at all, but the same issue exists for converting "):" to "," and it would generally be a useful feature to have.

**Comment by Consolatis** [comment]
> press ESC and find "):" and select all

Yes one can return to single cursor mode and create a new set of multi cursors.
Personally, I'd prefer a find like feature (which doesn't create new cursors) which works for multiple cursors though.

**Comment by richrd** [comment]
Afaik sublime doesn't do this either so closing for now. It might be done in the future.
