### ISSUE TITLE
[Wishlist] Mark whitespaces at end of line

### ISSUE THREAD

**Issue by Consolatis** [richrd/suplemon#231]
Just like nano does and I actually find it quite useful.
Color should be configurable or defined inside the syntax highlighting theme.

**Comment by richrd** [comment]
This can be achieved also by turning on whitespace marking in general. It can be toggled with F7. I don't think I'll be adding a special feature for showing just the whitespace at the end of the line. I think it might be more useful to instead have a plugin that automatically removes trailing whitespace.
