### ISSUE TITLE
[Wishlist] configuration utility

### ISSUE THREAD

**Issue by Consolatis** [richrd/suplemon#237]
Categories:
  - Colors (including live preview of color/attributes)
  - Keybindings (including capturing keys like "press key combination")
  - Layout
    - Show top bar
    - Show bottom bar
    - Show legend
    - Show linenumbers
  - SyntaxHLthemes (including live preview, may be useful or not)
  - Advanced (show and configure the whole of defaults.json merged with all runtime generated module configs)

Input: same config merges as within suplemon itself.
Output: ~/.config/suplemon/suplemon-{config, keymap}.json with everything differing from default.

Ncurses forms may be of help here.
Alternatively the "Advanced" category could be provided by suplemon showing a newly generated json file with the whole config + user config merged and when saving only saves the differences to defaults.

It could be its own utility or implemented as a ncurses.Panel overlay within suplemon itself.

If Top/Bottom bar is enabled it could show a list of all available StatusComponents (including description using the class's docstring) to select from.

**Comment by richrd** [comment]
This would sure be handy. I won't be able to implement it at the moment due to some architectural restrictions but I'll consider adding this eventually to the rewrite branch.
