### ISSUE TITLE
Howto exit help?

### ISSUE THREAD

**Issue by bagage** [richrd/suplemon#250]
I must be dumb but I cannot find how to quit the help. 

I often mistype `ctrl+h` instead of `ctrl+s` and I end up in the help. But then I cannot find how to quit it without quitting suplemon completely (eg `ctrl+q`). I don't see any shortcut in the bottom bar to quit it:

![image](https://user-images.githubusercontent.com/1451988/55148692-fc115400-5148-11e9-9158-fe61479619b6.png)

Some keys I thought that could have worked:
- `ctrl+q`. Wrong: it quits suplemon completely.
- `Escape`: no effect. 
- `ctrl+h`: could toggle the help... but actually it does not.
- `ctrl+w` (close current tab): but it seems help is not a tab so nothing happened.

I saw #190 but since it was already closed I thought it would be better to create a new issue for that.

Thanks!

**Comment by Dune-jr** [comment]
Same!

**Comment by richrd** [comment]
`ctrl+w` is the correct shortcut for closing help and other tabs. It works fine for me, if it does nothing then the terminal or something else is probably overriding the shortcut. That said making ctrl+h toggle help could be neat.

**Comment by richrd** [comment]
Thanks to @caph
