### ISSUE TITLE
Cursor's move_up method ignores the delta parameter

### ISSUE THREAD

**Issue by Ryan1729** [richrd/suplemon#251]
As you can see [here](https://github.com/richrd/suplemon/blob/2b83225610959b8b4c10d0eba7eea9565561a24f/suplemon/cursor.py#L79-L87) the body of the method does not refer to the `delta` parameter, so the cursor will always only be moved up one line.

**Comment by richrd** [comment]
Thanks for noticing this, will fix it in the next version!
