### ISSUE TITLE
`ctrl+k` doesn't respect `n`/`N` when asking to close file

### ISSUE THREAD

**Issue by twolfson** [richrd/suplemon#49]
I stumbled across the `ctrl+k` command when attempting to delete a line as in Sublime Text (i.e. `ctrl+k,ctrl+k`). This seems to be bound to a "Close File" command but it isn't respecting when I say "N":

Opened new file:

![selection_131](https://cloud.githubusercontent.com/assets/902488/7802823/fafbf026-0303-11e5-9a44-f719e8050cad.png)

Pressed `ctrl+k`:

![selection_132](https://cloud.githubusercontent.com/assets/902488/7802824/033a269a-0304-11e5-8ac3-d6b077dabf16.png)

Typed `N` and pressed enter:

![selection_133](https://cloud.githubusercontent.com/assets/902488/7802830/103c2118-0304-11e5-9262-6b88b8d16282.png)

Expected behavior: File does not close

Actual behavior: Buffer resets or file closes (not sure which)

OS information: Running on `bash@4.3.11(1)` on Linux Mint 17.1 64 bit

**Comment by richrd** [comment]
Hi!
Sorry about that one, and thanks for the thorough bug report :). I fixed it in the dev branch just now. I'll merge it to master when I review my changes.

I could also think about changing the default key binding for Ctrl + K. What do you think?

**Comment by twolfson** [comment]
Awesome, thanks =)

I am all for getting the keybindings as close to Sublime Text as possible. It would make reuse across the applications easy =)

For what it's worth, ST uses `ctrl+w` for its `close` command:

https://github.com/randy3k/sublime-default/blob/5c296d63820968a1fe1e0c9a54cb0a2cd7c65595/Default%20%28Linux%29.sublime-keymap#L13

**Comment by twolfson** [comment]
I have tried out the fix and verified it works. Thanks for the fix =)
