### ISSUE TITLE
Status bar items from plugins can't be ordered.

### ISSUE THREAD

**Issue by richrd** [richrd/suplemon#57]
Define way to specify status priority to use for ordering statuses properly.

**Comment by richrd** [comment]
I would like some input on this. I'm willing to refactor the status bar API completely, since it is limited. Later I would like to add color support and other fancy things.

@twolfson @abl and all others: How do you think modules could define their position in status bars? I was thinking of an index based approach where lower indices are further on the left, and higher indices further to the right. I think the `Suplemon Editor vX.X.X` could have an index of 0 and the max recommended index could be 100. This way one could specify priority (and even insert something before the app name: index < 0 or after everything else: index > 100). It would also be smart to define a guideline on how to choose an index for specific types of status info. 

Any suggestions?

**Comment by twolfson** [comment]
The simplest solution (which is what Sublime does) would be to use alphabetical sorting based on the key used. It would prevent needing to promote items to `dict's` and keep things baked in. If someone needs front priority, then they can use `000_my_key`. If they need last priority, then they can use `zzz_my_key`.

<img width="280" alt="screen shot 2015-10-07 at 2 24 08 pm" src="https://cloud.githubusercontent.com/assets/902488/10348574/65c3cffe-6cff-11e5-85ad-c3ed76b01ccd.png">

**Comment by Consolatis** [comment]
> I would like some input on this.
> I'm willing to refactor the status bar API completely, since it is limited.
> Later I would like to add color support and other fancy things.

I implemented a new StatusBarComponent architecture: StatusBar + StatusBarManager + StatusBarComponent + StatusBarFill.
The end result is you have status components which can be exposed by any module and used by any statusbar. It is configured via default config like this:
```
    "display": {
        "show_top_bar": true,
        "status_top": {
            "components": "editor_logo editor_name editor_version fill filelist fill clock",
            "fillchar": " ",
            "spacechar": " ",
            "truncate": "left",
            "default_align": "left"
        },
        "show_bottom_bar": true,
        "status_bottom": {
            "components": "app_status fill document_position Cursors cursor_count lint_error_count",
            "fillchar": " ",
            "spacechar": " ",
            "truncate": "right",
            "default_align": "left"
        },
        ..
    }
```
If a user wants to change it (e.g. remove the cursor count and move the lint error count to the left) all s/he needs to do is something like:
```
    "display": {
        "status_bottom": {
            "components": "lint_error_count app_status fill document_position"
        }
    }
```
"fill" works by calculating the unused space and distributing it evenly between all fill components:
- "clock fill clock" would result in a clock on the left and one on the right,
- "fill clock fill" would result in a single clock in the middle,
- "clock fill filelist fill clock" would result in a clock on the left and on the right and the filelist in the middle.

A StatusbarComponent provides essentially a unicode .text and currently a curses .style property.
Additionally it automatically calculates and caches the required cell width if .text changes.
It also provides a .compute() function which allows the component to update it's internal value and tell the caller if something has been changed.

Everything is cached and checked for changes before being written.
If no component changed it's value and there is no change in window size either the bar update does not render anything.

I primarily made this for my own usage but would like to upstream those changes after cleaning up and polishing it a bit if the design itself sounds reasonable.

**Comment by richrd** [comment]
Seems pretty cool! What does the .style property do?

**Comment by Consolatis** [comment]
The .style property is currently used as second argument to status_window.addstr().
The filelist module uses it for example with curses.A_BOLD for the active file and curses.A_DIM for the others. It could also be a color_pair.

"Currently" because I also implemented a color manager for the whole of Suplemon so it only uses strings for color pairs (which may have attached attributes as well). My default config defines those pairs for different color counts:
```
        "colors_8": {
            "status_top":             { "fg": "yellow",  "bg": "black" },
            "status_files_active":    { "fg": "white",   "bg": "black", "attribs": [ "bold" ] },
            "status_files_inactive":  { "fg": "white",   "bg": "black", "attribs": [ "dim"  ] },
            "status_bottom":          { "fg": "yellow",  "bg": "black" },
            "status_location":        { "fg": "white",   "bg": "black", "attribs": [ "dim"  ] },
            "linenumbers":            { "fg": "yellow",  "bg": "black" },
            "linenumbers_lint_error": { "fg": "red",     "bg": "black" },
            "status_warn":            { "fg": "red",     "bg": "black", "attribs": [ "dim"  ] },
            "editor":                 { "fg": "default", "bg": "default" },
            "editor_whitespace":      { "fg": "default", "bg": "default", "attribs": [ "dim" ] }
        },
        "colors_256": {
            "status_top":             { "fg": "yellow",   "bg": "black" },
            "status_files_active":    { "fg": "white",    "bg": "black" },
            "status_files_inactive":  { "fg": "color240", "bg": "black" },
            "status_bottom":          { "fg": "yellow",   "bg": "black" },
            "status_location":        { "fg": "color240", "bg": "black" },
            "linenumbers":            { "fg": "yellow",   "bg": "black" },
            "linenumbers_lint_error": { "fg": "color204", "bg": "black", "attribs": [ "bold" ] },
            "status_warn":            { "fg": "color204", "bg": "black" },
            "editor":                 { "fg": "default",  "bg": "default" },
            "editor_whitespace":      { "fg": "default",  "bg": "default", "attribs": [ "dim" ] }
        }
```
Syntax highlighting creates new color pairs on demand / reuses previously created color pairs by simply using the integer which is currently used for the curses.color_pair as identifier for the color manager.
I did not want to mix those two features for upstreaming so I decided to implement one of them first, push that and implement the other after that.
