### ISSUE TITLE
Change #! for cross platform compatibility

### ISSUE THREAD

**Issue by abl** [richrd/suplemon#59]
Hi! Huge fan of the work you're doing.

If you change the #! to be "#!/usr/bin/env python3" suplemon will work on OS X (assuming python3, of course) without changes.

**Comment by richrd** [comment]
Thanks, good idea! I'll change this in the dev now :+1: .

**Comment by abl** [comment]
Thanks :D

Apologies for not just submitting PRs, but I'd have to get them approved, and going through that process feels a little silly for a single line suggestion. :)

**Comment by richrd** [comment]
No prob, I appreciate your input :) A one line change PR does seem a little silly to me too!
