### ISSUE TITLE
suplemon launcher (supl?) script

### ISSUE THREAD

**Issue by abl** [richrd/suplemon#60]
I'm trying to replace my use of nano and ST3 with suplemon; one thing that would be really helpful (and I'm currently hacking around with aliases) would be a launcher script in the style of "subl" for Sublime Text.

Currently, if I symlink cli.py to /usr/local/bin/supl it, of course, fails; this has the side effect of making it hard to write a Homebrew formula (which might get a lot of extra users of suplemon. :)

Something as simple as:

```shell
#!/bin/sh
TARGET=`readlink $0`
`dirname $TARGET`/cli.py $*
```

might work. Note that normally `readlink -f $0` would be ideal but the -f flag isn't supported on OS X. http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac goes in to a lot of detail.

**Comment by richrd** [comment]
Awesome to hear you are trying to move to suplemon! :beers: .

I'm also messing with aliases, and a launcher script in /usr/bin/. This isn't ideal, and eventually I'll have to package suplemon properly. For now though your suggestion sounds good and I'll test it out and add it if all works good :)

**Comment by richrd** [comment]
Suplemon now has a convenient launcher script `suplemon.py` and it's also installable via `setup.py`.
Closing this for now. Feel free to comment if there's still room for improvement.
