### ISSUE TITLE
Add support for Homebrew

### ISSUE THREAD

**Issue by abl** [richrd/suplemon#62]
One of the easiest ways to get this in the hands of a lot of users is creating a Homebrew formula - well, once OS X support is working 100% :)

I'm erring on the side of being overly detailed here - apologies if I'm covering familiar ground!

1. Homebrew relies on semver; I notice you went from "0.1.11" to "0.1.2" which, in semver, would be a step backwards. (0.1.2 < 0.1.11 < 0.1.12 < 0.1.20)
2. Homebrew requires a stable release - it's possible to also have a HEAD and Devel channel, but packages that only have HEAD/Devel are not available by default to users. The easiest way to accomplish this is by tagging releases - if you tag a release as `0.1.3` GitHub will automatically create a tarball.
3. Some kind of launcher script is necessary - it's possible to embed that in to the Homebrew formula, but it's frowned upon.

A formula for Suplemon would probably look like the following - copied and pasted from the Homebrew formula template.

```ruby
class Suplemon < Formula
  desc "Console text editor with multi cursor support. Suplemon replicates Sublime Text style functionality in the terminal."
  homepage "https://github.com/richrd/suplemon"
  version "0.1.3"
  url "https://github.com/richrd/suplemon/archive/0.1.3.tar.gz"
  head "https://github.com/richrd/suplemon.git"

  devel do
    url "https://github.com/richrd/suplemon.git", :using => :git, :branch => "dev"
    version "dev"
  end

  depends_on 'python3'
  depends_on 'coreutils' # greadlink for greadlink -f

  def install
    libexec.install Dir["*.py"]
    libexec.install Dir["modules"]
    libexec.install Dir["linelight"]
    bin.install "supl"
  end

end
```

Homebrew works by creating a series of symlinked repositories of various versions, etc - anything not specified during the install step is removed. (The formula spec makes a lot more sense when your last step is `make install`.) Here, I'm dumping everything in to libexec except for the supl launcher command; anything put in bin ends up on the user's path.

With this formula, a user could...

1. `brew install suplemon` to get 0.1.3
2. `brew install suplemon --HEAD` to get whatever is at the tip of master.
3. `brew install suplemon --devel` to get whatever is at the tip of dev. (`--devel` is supposed to be for alpha/canary versions; `--HEAD` is supposed to be for the literal bleeding edge - it might make sense to not support `--devel` and have `--HEAD` point to the dev branch.)

The `supl` command would probably look like...

```shell
#!/bin/sh
TARGET=`greadlink -f $0`
`dirname $TARGET`/../libexec/cli.py $*
```

The real thing should probably be a bit more intelligent (and useful for non-Homebrew users, of course. :)

**Comment by abl** [comment]
Also, feel free to ping me via my GitHub email - I can set up a shell account on one of my Macs if you'd like to test this out.

**Comment by abl** [comment]
All of this said, it probably makes more sense to package this up for pip - http://click.pocoo.org/ made it relatively painless to produce pip installable commandline tools.

**Comment by richrd** [comment]
Thanks for your help again! Sorry for not getting back to this earlier.

**Comment by richrd** [comment]
Thanks for your help again! Sorry for not getting back to this earlier.

I'll look into Homebrew packaging when OS X support is proper. I've never used it so most of your information was new to me. Also thanks for correcting my semver fail :). I could definitely benefit from a Mac shell account for testing this, but right now I'm still working on other parts of the editor. I'll let you know when I get back to this. :+1:

**Comment by richrd** [comment]
Hi again!

I've uploaded suplemon to pip, and I'm not currently considering creating a Homebrew package. Hopefully the pip package is sufficient.

I'm closing this for now but will reopen if I change my mind. :)
