### ISSUE TITLE
Auto hide keyboard shortcuts from status bar 

### ISSUE THREAD

**Issue by dufferzafar** [richrd/suplemon#70]
I think there should be a setting to hide the keyboard shortcuts in the status bar. Once you know all the hotkeys, there's not much point in displaying them always, IMHO.

**Comment by richrd** [comment]
Sure, it's already implemented :)

You can use F11 to toggle full screen mode (hides the status bars and keyboard legend).
You can also toggle the status bars and keyboard legend individually with the following settings:
 * ```show_top_bar```
 * ```show_bottom_bar```
 * ```show_legend```

To get rid of the legend put this in your config file (```~/.config/suplemon/suplemon-config.json```):
```
{
    "display": {
        "show_legend": 0
    }
}
```

The easiest way to edit your config is pressing ```Ctrl+E``` and running the ```config``` command. Suplemon will also automatically reload the config whenever you save the file.
Hope this helps.

**Comment by dufferzafar** [comment]
Wow, thanks for your quick response!

I didn't know there already was a config in place :smiley:

**Comment by richrd** [comment]
No prob!

I'll get the documentation improved ASAP. I've been doing some major developments lately. I hope to get them pushed to master soon :)
