### ISSUE TITLE
Installing system-wide

### ISSUE THREAD

**Issue by Calinou** [richrd/suplemon#75]
How can one install Suplemon system-wide, to invoke it with just `suplemon`? Is there any `pip` package or such?

**Comment by miohtama** [comment]
For system-wide installations the recommended path would be to wrap Suplemon to a native distribution package first:

E.g. Debian / Ubuntu https://pypi.python.org/pypi/stdeb https://wiki.debian.org/Python/Packaging

**Comment by richrd** [comment]
Thanks for asking!

Unfortunately I haven't got round to packaging Suplemon to pip yet. I've been busy getting some essential features implemented, and fixing some bugs. Now that you asked, I'll make packaging a priority.

For now as a quick workaround you could place the following file named `suplemon` in `/usr/bin/` and make it executable.
```
#!/bin/sh
python3 /path/to/suplemon/suplemon/cli.py $@
```

**Comment by Calinou** [comment]
> For now as a quick workaround you could place the following file named suplemon in /usr/bin/ and make it executable.

Wouldn't `/usr/local/bin` be a better place?

**Comment by richrd** [comment]
Yes, your right, thanks for the correction! :)

**Comment by richrd** [comment]
This is now finally fixed in the master branch! It took me longer than I thought, because it involved some majour refactoring etc. Hope you enjoy :) :beers:
