### ISSUE TITLE
F1 is help on many X teminals - allow ^S to save.

### ISSUE THREAD

**Issue by AlbericC** [richrd/suplemon#8]
As useful a quick F1 is, I can't save with suplemon out-of-the-box in a MATE terminal, because F1 invokes help. ctrl+S or ^S is very common and people are used to it, let's use this too.

**Comment by richrd** [comment]
Thanks for the info! :+1: I have the opposite problem since Ctrl+S is Suspend on my terminal.
I'll enable saving with Ctrl+S too asap. Also custom keybindings will be comming later.

**Comment by AlbericC** [comment]
thank you !

**Comment by richrd** [comment]
Your welcome!
