### ISSUE TITLE
Move default configuration into a JSON file.

### ISSUE THREAD

**Issue by richrd** [richrd/suplemon#80]
Also separate key bindings to a separate file, both in defaults and user configuration. This will make it easier to manage app and editor shortcuts. They too need to be unified so that the same key list is used for all shortcuts. Additionally the shortcuts need an argument list for extra granuality, like in Sublime Text.

**Comment by dufferzafar** [comment]
:+1:

**Comment by richrd** [comment]
Will be comming soon! :)

**Comment by richrd** [comment]
Fixed in v0.1.33. Available in master branch.
