### ISSUE TITLE
Ctrl + S doesn't seem to be working

### ISSUE THREAD

**Issue by dufferzafar** [richrd/suplemon#82]
For me, `Ctrl + S` doesn't work, though `F1 - Save As` works as expected.

I am on Ubuntu 14.04 using the latest master branch.

At first I thought this was due to my terminal ([Gnome Terminator](http://gnometerminator.blogspot.com/p/introduction.html)) or shell (Zsh), but I then tested it with the stock ubuntu terminal too. No luck.

I guess this is related to Ctrl + Q. Since [Ctrl + S is suspend mode](http://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal), right?

**Comment by richrd** [comment]
Yep, you're totally right. Ctrl+S doesn't work on terminals that use it for suspend. I had to disable that feature on my terminal.

I have found a fix for it, but I need to test it out before pushing to master.
I'll push the fix to the dev branch soon.

Thanks for the report! :+1:

**Comment by richrd** [comment]
Hi, good news!

I changed the curses terminal mode in the Suplemon UI from `raw` to `cbreak`. That should disable special terminal keys. I tested it on my Ubuntu virtual machine, and seems like it works fine. Could you test the `dev` branch to verify it works? I would really appreciate it :+1: 

Thanks!

**Comment by dufferzafar** [comment]
Congratulations! It seems to be working fine now. Thanks again for making such a nice tool.

**Comment by richrd** [comment]
No problem, nice to hear you like it!
