### ISSUE TITLE
Pasting text from system clipboard

### ISSUE THREAD

**Issue by dufferzafar** [richrd/suplemon#84]
Pasting text from system clipboard messes up the entire layout, as random whitespace gets inserted in the beginning of the text. 

It is also, quite slow, as the all the text seems to get "typed" on the screen.

I copied & pasted this text:

```cpp
#include "GL/freeglut.h"
#include "GL/gl.h"

/* display function - code from:
     http://fly.cc.fer.hr/~unreal/theredbook/chapter01.html
This is the actual usage of the OpenGL library. 
The following code is the same for any platform */
void renderFunction()
{
    glClearColor(0.0, 0.0, 0.0, 0.0);
    glClear(GL_COLOR_BUFFER_BIT);
    glColor3f(1.0, 1.0, 1.0);
    glOrtho(-1.0, 1.0, -1.0, 1.0, -1.0, 1.0);
    glBegin(GL_POLYGON);
        glVertex2f(-0.5, -0.5);
        glVertex2f(-0.5, 0.5);
        glVertex2f(0.5, 0.5);
        glVertex2f(0.5, -0.5);
    glEnd();
    glFlush();
}

/* Main method - main entry point of application
the freeglut library does the window creation work for us, 
regardless of the platform. */
int main(int argc, char** argv)
{
    glutInit(&argc, argv);
    glutInitDisplayMode(GLUT_SINGLE);
    glutInitWindowSize(500,500);
    glutInitWindowPosition(100,100);
    glutCreateWindow("OpenGL - First window demo");
    glutDisplayFunc(renderFunction);
    glutMainLoop();    
    return 0;
}
```

And this is how suplemon looked after the paste:

![Suplemon](http://i.imgur.com/mP8AfLd.png)

The pasting procedure took around 6-7 seconds to complete since the text was sort-of getting typed animatedly.

**Comment by richrd** [comment]
Hi! 

System clipboard syncing is already available, but you need to install `xsel` for it to work. On Ubuntu/Debian: `sudo apt-get install xsel` after that you can just use Ctrl+V and Ctrl+C normally :)
Can you let me know if you get it working?

When syncing is on Suplemon will get the system clipboard and paste it properly. Also when you copy in Suplemon, it will place copied text to system clipboard. *This only works locally, not over SSH.*

The random whitespace is actually the auto indent feature. It indents each new line to the same level as the previous line. So when the pasted text contains a new line, Suplemon indents it even though the next line already has indentation. (It can be toggled in the config with `auto_indent_newline`. https://github.com/richrd/suplemon/blob/01f4244c4a35338a084c6cc7dbe6a868136e5af4/suplemon/config/defaults.json#L41) Your custom config file should be placed in `~/.config/suplemon/suplemon-config.json`

**Comment by dufferzafar** [comment]
I keep forgetting that Suplemon is more sublime than vim, so I was trying to paste the text using `Ctrl + Shift + V` hotkey which basically sends text to a terminal.

I already had `xsel` installed, so `Ctrl + V` works nicely. :)

**Comment by meoso** [comment]
could auto-indent turn off for pastes only?

**Comment by richrd** [comment]
@meoso Yes it can! Suplemon can't detect a `Ctrl + Shift + V` paste, but you can activate paste mode by pressing `Ctrl + E` and running `paste`. That toggles paste mode (which disables auto-indent).

You don't have to do that if you are pasting with `Ctrl + V` as that uses the system clipboard integration. However that doesn't work over SSH so you must use paste mode and `Ctrl + Shift + V`.
