### ISSUE TITLE
no colors in TTY

### ISSUE THREAD

**Issue by AlbericC** [richrd/suplemon#9]
suplemon renders colors perfectly in a graphical terminal, yet it does not issue colors in a standard TTY on my machine. It may have to be double checked as my machine could be unusual.

**Comment by richrd** [comment]
Thanks, I'll look into this.

**Comment by richrd** [comment]
I checked this, and I have the same problem. I'll see how to fix this.

**Comment by richrd** [comment]
Apparently Suplemon tries to use better colors event when the TTY only supports 8 colors.
Suplemon simply tries to use colors that aren't supported (color number > 8). Will fix this.

**Comment by richrd** [comment]
My assumption was correct. Suplemon uses colors 11-17 wich won't work when only 8 colors are supported.

**Comment by richrd** [comment]
Now fixed in 0.1.2.
Just make sure your TERM variable is set to "xterm" when using a TTY.
